"""FastAPI app entrypoint. Models live in app/models.py (generated by model_generator)."""
from fastapi import FastAPI

app = FastAPI(title="Policy Engine")


@app.get("/")
def root():
    return {"service": "Policy Engine", "models": "app.models"}


@app.get("/health")
def health():
    return {"status": "ok"}
